image: python:latest

docker: 
  image: docker:20.10.6
  services: ['docker;20.10.6-dind']##dind??
  
  before_script:
  

  script:

 
building:
  stage: build

  script: 
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt

    python src/read_data.py
    python src/text_preprocessing.py
    python src/text_classification.py

    python src/serve_model.py
